/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package es.prodevelop.testar.api.controller;

import es.prodevelop.testar.api.model.Params;
import es.prodevelop.testar.api.model.ReturnExecution;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-05T15:16:04.078Z")

@Api(value = "Default", description = "the Default API")
public interface DefaultApi {

    @ApiOperation(value = "execute TESTAR", nickname = "execute", notes = "Invoking execution TESTAR by command line ", response = ReturnExecution.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "TESTAR executed successfully", response = ReturnExecution.class),
        @ApiResponse(code = 400, message = "invalid input, object params invalid") })
    @RequestMapping(value = "/testar",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ReturnExecution> execute(@ApiParam(value = "Inventory item to add"  )  @Valid @RequestBody Params params);

}
