/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package es.prodevelop.testar.api.controller;

import es.prodevelop.testar.api.model.TestarFile;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-06T15:38:51.885Z")

@Api(value = "Sequences", description = "the Sequences API")
public interface SequencesApi {

    @ApiOperation(value = "Sequence files", nickname = "getSequenceFiles", notes = "returns files of last execution sequence", response = TestarFile.class, responseContainer = "List", tags={ "Sequences", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "DeviceStatus", response = TestarFile.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "bad request"),
        @ApiResponse(code = 404, message = "Not found. A device with the requested name was not found") })
    @RequestMapping(value = "/sequences/{sequenceId}",
        method = RequestMethod.GET)
    ResponseEntity<List<TestarFile>> getSequenceFiles(@ApiParam(value = "",required=true) @PathVariable("sequenceId") String sequenceId);

}
